"""graduate name addition

Revision ID: 11b44f93b366
Revises: 7e82a438d5c3
Create Date: 2023-11-18 18:29:49.046327

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "11b44f93b366"
down_revision = "7e82a438d5c3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "graduates", sa.Column("graduate_name", sa.String(length=2004), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("graduates", "graduate_name")
    # ### end Alembic commands ###
