"""graduate year

Revision ID: 52f1cceb2d2c
Revises: ca717b9cd75a
Create Date: 2024-03-26 11:17:09.017808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52f1cceb2d2c'
down_revision = 'ca717b9cd75a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('graduates', sa.Column('graduate_year', sa.String(length=2004), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('graduates', 'graduate_year')
    # ### end Alembic commands ###
