"""minor fix

Revision ID: 9bdf09e2a5b6
Revises: f6d00e624e52
Create Date: 2024-04-19 03:50:26.447623

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9bdf09e2a5b6"
down_revision = "f6d00e624e52"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
