"""reverting to previous

Revision ID: c6dcaf42ec7c
Revises: 9bdf09e2a5b6
Create Date: 2024-04-19 03:55:01.818352

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c6dcaf42ec7c"
down_revision = "9bdf09e2a5b6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
