"""final additions

Revision ID: d25d7d8ee9b7
Revises: 11b44f93b366
Create Date: 2023-11-18 20:23:17.606064

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "d25d7d8ee9b7"
down_revision = "11b44f93b366"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "comments",
        sa.Column("name_of_commenter", sa.String(length=2004), nullable=True),
    )
    op.add_column(
        "comments",
        sa.Column("graduate_id", postgresql.UUID(as_uuid=True), nullable=True),
    )
    op.drop_constraint("comments_user_id_fkey", "comments", type_="foreignkey")
    op.create_foreign_key(None, "comments", "graduates", ["graduate_id"], ["id"])
    op.drop_column("comments", "user_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "comments",
        sa.Column("user_id", postgresql.UUID(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "comments", type_="foreignkey")
    op.create_foreign_key(
        "comments_user_id_fkey", "comments", "graduates", ["user_id"], ["id"]
    )
    op.drop_column("comments", "graduate_id")
    op.drop_column("comments", "name_of_commenter")
    # ### end Alembic commands ###
