"""Added features

Revision ID: f6d00e624e52
Revises: ff5421c60a0c
Create Date: 2024-04-19 03:36:39.617742

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f6d00e624e52"
down_revision = "ff5421c60a0c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chat_rooms",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("chat_name", sa.String(length=2004), nullable=True),
        sa.Column("chat_description", sa.String(length=2004), nullable=True),
        sa.Column("chat_picture", sa.String(length=2004), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_chat_rooms_id"), "chat_rooms", ["id"], unique=False)
    op.create_table(
        "colleges",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("college_name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_colleges_id"), "colleges", ["id"], unique=False)
    op.create_table(
        "country",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("country_name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_country_id"), "country", ["id"], unique=False)
    op.create_table(
        "courses",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("course_name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_courses_id"), "courses", ["id"], unique=False)
    op.create_table(
        "gender",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("gender_name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_gender_id"), "gender", ["id"], unique=False)
    op.create_table(
        "job_titles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("job_name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_job_titles_id"), "job_titles", ["id"], unique=False)
    op.create_table(
        "opportunity_type",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("type_name", sa.String(length=2004), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_opportunity_type_id"), "opportunity_type", ["id"], unique=False
    )
    op.create_table(
        "chat_messages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("chat_id", sa.UUID(), nullable=True),
        sa.Column("graduate_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["chat_id"],
            ["chat_rooms.id"],
        ),
        sa.ForeignKeyConstraint(
            ["graduate_id"],
            ["graduates.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_chat_messages_id"), "chat_messages", ["id"], unique=False)
    op.create_table(
        "news_updates",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("title", sa.String(length=2004), nullable=True),
        sa.Column("description", sa.String(length=2004), nullable=True),
        sa.Column("media", sa.String(length=2004), nullable=True),
        sa.Column("poster_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["poster_id"],
            ["graduates.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_news_updates_id"), "news_updates", ["id"], unique=False)
    op.create_table(
        "notifications",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("title", sa.String(length=2004), nullable=True),
        sa.Column("details", sa.String(length=2004), nullable=True),
        sa.Column("graduate_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["graduate_id"],
            ["graduates.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_notifications_id"), "notifications", ["id"], unique=False)
    op.create_table(
        "opportunities",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("title", sa.String(length=2004), nullable=True),
        sa.Column("description", sa.String(length=2004), nullable=True),
        sa.Column("media", sa.String(length=2004), nullable=True),
        sa.Column("opportunity_type_id", sa.UUID(), nullable=True),
        sa.Column("poster_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["opportunity_type_id"],
            ["opportunity_type.id"],
        ),
        sa.ForeignKeyConstraint(
            ["poster_id"],
            ["graduates.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_opportunities_id"), "opportunities", ["id"], unique=False)
    op.add_column(
        "graduates",
        sa.Column("graduate_reference_number", sa.String(length=2004), nullable=True),
    )
    op.add_column(
        "graduates", sa.Column("place_of_work", sa.String(length=2004), nullable=True)
    )
    op.add_column(
        "graduates", sa.Column("password", sa.String(length=2004), nullable=True)
    )
    op.add_column("graduates", sa.Column("otp", sa.String(length=2004), nullable=True))
    op.add_column(
        "graduates", sa.Column("email", sa.String(length=2004), nullable=True)
    )
    op.add_column(
        "graduates", sa.Column("phone_number", sa.String(length=2004), nullable=True)
    )
    op.add_column("graduates", sa.Column("job_id", sa.UUID(), nullable=True))
    op.add_column("graduates", sa.Column("course_id", sa.UUID(), nullable=True))
    op.add_column("graduates", sa.Column("college_id", sa.UUID(), nullable=True))
    op.add_column("graduates", sa.Column("country_id", sa.UUID(), nullable=True))
    op.add_column("graduates", sa.Column("gender_id", sa.UUID(), nullable=True))
    op.create_foreign_key(None, "graduates", "gender", ["gender_id"], ["id"])
    op.create_foreign_key(None, "graduates", "country", ["country_id"], ["id"])
    op.create_foreign_key(None, "graduates", "courses", ["course_id"], ["id"])
    op.create_foreign_key(None, "graduates", "colleges", ["college_id"], ["id"])
    op.create_foreign_key(None, "graduates", "job_titles", ["job_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "graduates", type_="foreignkey")
    op.drop_constraint(None, "graduates", type_="foreignkey")
    op.drop_constraint(None, "graduates", type_="foreignkey")
    op.drop_constraint(None, "graduates", type_="foreignkey")
    op.drop_constraint(None, "graduates", type_="foreignkey")
    op.drop_column("graduates", "gender_id")
    op.drop_column("graduates", "country_id")
    op.drop_column("graduates", "college_id")
    op.drop_column("graduates", "course_id")
    op.drop_column("graduates", "job_id")
    op.drop_column("graduates", "phone_number")
    op.drop_column("graduates", "email")
    op.drop_column("graduates", "otp")
    op.drop_column("graduates", "password")
    op.drop_column("graduates", "place_of_work")
    op.drop_column("graduates", "graduate_reference_number")
    op.drop_index(op.f("ix_opportunities_id"), table_name="opportunities")
    op.drop_table("opportunities")
    op.drop_index(op.f("ix_notifications_id"), table_name="notifications")
    op.drop_table("notifications")
    op.drop_index(op.f("ix_news_updates_id"), table_name="news_updates")
    op.drop_table("news_updates")
    op.drop_index(op.f("ix_chat_messages_id"), table_name="chat_messages")
    op.drop_table("chat_messages")
    op.drop_index(op.f("ix_opportunity_type_id"), table_name="opportunity_type")
    op.drop_table("opportunity_type")
    op.drop_index(op.f("ix_job_titles_id"), table_name="job_titles")
    op.drop_table("job_titles")
    op.drop_index(op.f("ix_gender_id"), table_name="gender")
    op.drop_table("gender")
    op.drop_index(op.f("ix_courses_id"), table_name="courses")
    op.drop_table("courses")
    op.drop_index(op.f("ix_country_id"), table_name="country")
    op.drop_table("country")
    op.drop_index(op.f("ix_colleges_id"), table_name="colleges")
    op.drop_table("colleges")
    op.drop_index(op.f("ix_chat_rooms_id"), table_name="chat_rooms")
    op.drop_table("chat_rooms")
    # ### end Alembic commands ###
